### ISSUE TITLE
PSR-4 support

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#17]
Since [PSR-0 is marked as deprecated](http://www.php-fig.org/psr/psr-0/), support for PSR-4 which involves namespaces and per-file classes would be nice.

**Comment by pocesar** [comment]
that would definitely break existing implementations. would need to refactor for a 3.x version

**Comment by holtkamp** [comment]
indeed, this would justify a 3.x release. Do you got time for this? I might be able to help :+1:

**Comment by pocesar** [comment]
not right now, but will eventually. the classes need to be split into files, then namespaced accordingly, if you can help, would be great :)

**Comment by holtkamp** [comment]
yeah, seems feasible. Am I correct that no tests are in place yet?

**Comment by pocesar** [comment]
there aren't, because it's really hard to 'cross test' between PHP and the browser in an automated way (tried and failed)
