### ISSUE TITLE
Package name inconsistency

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#20]
While working at https://github.com/pocesar/phery/issues/17 in a separate [branch](https://github.com/holtkamp/phery/tree/psr-4), some inconsistencies were identified in the package name:

- name on [Packagist](https://packagist.org/packages/phery/phery) is ```phery/phery```
- name in ```composer.json``` is ```phery/phery.js```

So what is it? I guess it would be ```phery/phery```.

Additionally you might want to condsider to move the package away from your personal GitHub account to its own 'phery' organization on GitHub. Also see [this motivation](https://t37.net/here-comes-the-time-to-hand-over-your-open-source-project.html).

**Comment by pocesar** [comment]
it should be phery.js, because it's mainly a frontend library, the PHP part is just the bridge :)

moved to https://github.com/pheryjs/phery

**Comment by holtkamp** [comment]
Ok, but what came to mind, should this not be better / future proof:
- (GitHub) organization / vendor name: Phery (this would also be the main/vendor namespace)
- library name: PheryJS

Using this approach, if in the future any other library will be developed, this can be easily done: ```phery/libraryX```, or ```phery/pluginY```.

In terms of consistency, in that case the PHP namespace should also become: ```Phery\PheryJS``` in the 3.0 branch... Also see the PSR-4 specs: http://www.php-fig.org/psr/psr-4/

**Comment by pocesar** [comment]
https://github.com/phery is taken =/

**Comment by holtkamp** [comment]
>it should be phery.js, because it's mainly a frontend library, the PHP part is just the bridge :)

Ok, so for a fresh install I had in my ```composer.json```: 

```
require: {
    "phery/phery.js": "dev-3.0.0-alpha.1"
}
```

Which resulted in:
```
- The requested package phery/phery.js could not be found in any version, there may be a typo in the package name.
```

On packagist the name is ```phery/phery```, maybe "move" that one to ```phery/phery.js``` ([explained here](https://twitter.com/matthieunapoli/status/591536696618942464)) as well as part of the upgrade to 3.0?

Then this issue can be closed I guess...

**Comment by pocesar** [comment]
alright, created `phery/phery.js`. Need to update the README.md with the new composer installation instructions

**Comment by holtkamp** [comment]
great, together with the [Composer Asset Plugin](https://github.com/francoispluchino/composer-asset-plugin) (to make sure the Javascript files are installed in a publicly accessible folder), this now works properly:

```
"require": {
	"bower-asset/phery.js": "dev-3.0.0-alpha.1",
	"phery/phery.js": "dev-3.0.0-alpha.1"
}
```

Closing issue.

**Comment by pocesar** [comment]
:+1:
