### ISSUE TITLE
Parameter type is lost when sending from Javascript to PHP

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#25]
For some reason, when trying to pass an array of integers, booleans and strings to PHP using Phery, they all end up to be strings:

```html
<input type="text"
  id="elementID"
  value="10" 
  data-parameter-integer="10"
  data-parameter-boolean-true="true"
  data-parameter-boolean-false="false"
  data-parameter-string="string" />
```

```javascript
$("#elementID").change(function() {
	console.log($(this).data()); //Shows an object
	phery.remote("remoteFunction", $(this).data() );
} );
```

When outputting the parameters received by PHP, this results in:

```php
array(4) {
  ["parameterInteger"] => string(2) "10"
  ["parameterBooleanTrue"] => string(4) "true"
  ["parameterBooleanFalse"] => string(5) "false"
  ["parameterString"] => string(6) "string"
}
```

The [phery.remote()](https://github.com/pheryjs/phery#pheryremotefunction_name-args-attr-direct_call) and [jquery.data()](http://api.jquery.com/data/#data-html5) documentation clearly indicate this approach should work and the parameter types should be preserved in PHP. Any idea why the values are converted to string? Maybe because they are sent as POST / application/x-www-form-urlencoded? I had a look at the involved `functions.per_data() ` function, and that seems to be responsible to do what I expect...

UPDATE
[All values that are sent using GET/POST are strings](http://stackoverflow.com/questions/14716730/send-a-boolean-value-in-jquery-ajax-data). Is there a way to force Phery to use JSON to ensure the data types of the submitted values do not get lost?

**Comment by holtkamp** [comment]
Ok, taking into account that the POSTed values are all strings by the time they reach PHP, the intermediate solution seems to:

- encode the Javascript values to a JSON string at the client
- decode the JSON string to PHP values in PHP

```javascript
phery.remote("remoteFunctionAtBackend", JSON.stringify($(this).data()) );
```

```php
public function remoteFunctionAtBackend(array $ajaxData, array $callbackData)
{
	$ajaxData = json_decode(current($ajaxData));
}
```

This results in an object like:

```php
object(stdClass)#4974 (4) {
  ["parameterInteger"] => int(10)
  ["parameterBooleanTrue"] => bool(true)
  ["parameterBooleanFalse"] => bool(false)
  ["parameterString"] => string(6) "string"
}
```

It would be nice to be able to *configure* Phery in such a way that these steps are done automatically... Using JSON to send over parameters is the default 'transport' mode in Xajax.

**Comment by pocesar** [comment]
the problem is the `application/x-www-form-urlencoded` or `multipart/form-data` that is needed for uploads to work. when using `application/json`, and configuring jQuery to send the data as JSON to the client, you lose the ability to send form data along with files. 

I know most of the time it's a command sent over a click on a link / button, with some data attached to it. but for a full blown form with many files, it's needed to 'cover all the bases'.
there's nothing that stops you using a pre filter to transform the json data, like you did.

```php
function jsonencodeit($ajax_data)
{
   try {
      $decoded = json_decode($ajax_data);
      if (json_last_error() == JSON_ERROR_NONE){
          return $decoded;
      }
   } catch (Exception $e) {
   }

   return $ajax_data;
}

Phery::instance()->callback(array(
        'before' => array('jsonencodeit'),
));
```

this will work for all calls within the same instance. it tries to decode JSON, if fails, it keeps the data as-is.

**Comment by holtkamp** [comment]
thanks for the explanation, already used some nice 'after' callbacks today, so this fits in nice :+1: . 

Closing issue.
