### ISSUE TITLE
Chaining PheryResponses that do not have a selector using PheryResponses::add() results in empty response

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#26]
When using this approach to chain / stack responses easily in PHP:
```php
$response = PheryResponse::factory(); //Note that no selector is used
$response->add(PheryResponse::factory('#element')->html('elementContentGoesHere');
$response->add($this->processSomeStuffAndReturnAPheryResponse());
```
The result is an empty object: ```{}``` when returned to the client.

When using a dummy selector, it works though:

```php
$response = PheryResponse::factory(__FUNCTION__); //Note that a dummy selector is used
$response->add(PheryResponse::factory('#element')->html('elementContentGoesHere');
$response->add($this->processSomeStuffAndReturnAPheryResponse());
```

It seems that a (last) selector had to be set for the ```PheryResponse::add()``` function to work properly. Is this intended? When removing the [check for a 'lastSelector' in ```PheryResponse::__call()```](https://github.com/pheryjs/phery/blob/fca4dd87f1b9409c3c52981482501b85b63bcfcf/src/Phery/PheryResponse.php#L1402), it works properly, but I can not oversee the implications of this for other functionality since the documentation of that function states:

*"To reach this magically called functions, the jquery() selector must be called prior to any jquery specific call"*

What is the rationale for this condition? No need to reach anything to add it, right?

**PheryResponse::merge()**
Merging does work when no selectors are involved, since it does not go 'through' the ```PheryResponse::__call()``` method, only the order is reverted, so I would prefer to use the ```PheryResponse::add()```, or am expecting the wrong behaviour here?

```php
$response = PheryResponse::factory();
$response->merge(PheryResponse::factory('#element')->html('elementContentGoesHere');
$response->merge($this->processSomeStuffAndReturnAPheryResponse());
```

**Comment by pocesar** [comment]
the `add` method is the `jQuery.add()`, it's used to "aggregate" many sets of elements. the `PheryResponse::merge` is specific to Phery to, well, merge responses. So it's the way to go. 
The calls to subsequent jquery methods need to be, at least, be defined to a selector, unless it's a static function, like `PheryResponse::factory()->jquery->someFn()` (that translates to `$.someFn`). 
An initial selector is needed to diferentiate between PheryResponse internal class calls, object methods and jquery related stuff

**Comment by holtkamp** [comment]
ok, thanks for the detailed response, will try to keep track of these things to come up with a 'guide for beginners' section in the documentation :+1: 

Closing issue

**Comment by pocesar** [comment]
:+1:
