### ISSUE TITLE
Add bower.json to increase ease of installation

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#27]
To stimulate adoption and increase ease of installation during development, a ```bower.json``` file would be useful.

Personally I use https://packagist.org/packages/fxp/composer-asset-plugin to make sure I can include this in my ```composer.json```: ```bower-asset/phery``` to have the files as defined in ```bower.json``` installed in a ```public/assets``` folder.

**Comment by pocesar** [comment]
how does that work? and how to configure it? if you have a working PR to merge to 3.0.0-alpha would be nice
