### ISSUE TITLE
Register at CDN to increase ease of deployment

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#28]
To stimulate adoption and increase ease of deployment during production, registration of the Javascript files at a CDN like http://www.cdnjs.com is useful.

**Comment by holtkamp** [comment]
FYI, working on this, CDNJS is always a challenge though.. GitHub considers the new branch to be 'totally different:

<img width="1008" alt="screen shot 2016-10-15 at 19 34 07" src="https://cloud.githubusercontent.com/assets/776405/19412095/7f32b938-930e-11e6-9221-40c4e60fa5ad.png">


Steps:
```
git init cdnjs && cd cdnjs
git config core.sparseCheckout true
echo '/package.json' >> .git/info/sparse-checkout
echo '/auto-update.js' >> .git/info/sparse-checkout
echo '/test/*' >> .git/info/sparse-checkout
echo '/ajax/libs/phery.js/*' >> .git/info/sparse-checkout
git reset --hard
git remote add origin https://github.com/holtkamp/cdnjs.git
git remote add upstream https://github.com/cdnjs/cdnjs.git
git pull upstream master --depth 1
git checkout -b patch-phery.js-autoupdate
mkdir -p ajax/libs/phery.js
cd ajax/libs/phery.js
//added package.json file
git add package.json
git commit -m "Enable phery.js autoupdate"
git push --set-upstream origin patch-phery.js-autoupdate
cd ../..
npm install
npm test
```

**Comment by holtkamp** [comment]
Update, this approach did the trick:

```
git init cdnjs && cd cdnjs
git config core.sparseCheckout true
echo '/package.json' >> .git/info/sparse-checkout
echo '/auto-update.js' >> .git/info/sparse-checkout
echo '/test/*' >> .git/info/sparse-checkout
echo '/ajax/libs/phery.js/*' >> .git/info/sparse-checkout
git reset --hard
git remote add origin https://github.com/holtkamp/cdnjs.git
git remote add upstream https://github.com/cdnjs/cdnjs.git
git pull upstream master --depth 1
git checkout -b patch-phery.js-autoupdate
mkdir -p ajax/libs/phery.js
cd ajax/libs/phery.js
//added package.json file
git add package.json
git commit -m "Enable phery.js autoupdate"
git push --set-upstream origin HEAD:patch-phery.js-autoupdate
HEAD:
cd ../..
npm install
npm test
```

PR submitted: https://github.com/cdnjs/cdnjs/pull/9284

**Comment by pocesar** [comment]
so this need to become it's own branch? or another repo?

**Comment by holtkamp** [comment]
@pocesar, by submitting a ```package.json``` to CDNJS with an autoupdate section, nothing has to change actually. CDNJS will monitor the activity of this repo. As soon as a new version is tagged, it will be detected and adopted in their CDN 😄

**Comment by holtkamp** [comment]
victory, it has been merged: https://github.com/cdnjs/cdnjs/pull/9284

**Comment by holtkamp** [comment]
and published: https://cdnjs.com/libraries/phery.js

**Comment by pocesar** [comment]
ah nice, thanks!
