### ISSUE TITLE
Demo relies on missing colorbox

### ISSUE THREAD

**Issue by Chealer** [pheryjs/phery#32]
demo.php contains:
<script src="colorbox/colorbox/jquery.colorbox.js" id="colorbox-script" type="text/javascript"></script>
<link rel="stylesheet" href="colorbox/example1/colorbox.css">

The package (2.7.2) does not contain a colorbox/ directory, therefore this causes 404 errors when loading the page.

**Comment by pocesar** [comment]
thanks for the report, I've updated the demo.php to use CDN instead.
