### ISSUE TITLE
3.0.0 alpha 1 also requires jQuery 3.0

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#50]
Recent activity in this repo confused me. Our application which uses Phery does NOT support jQuery 3.0 yet, but has been using ```Phery 3.0.0 alpha 1``` for a while. 

https://github.com/pheryjs/phery/commit/2176ce7a5d95fafab9050203e9a26cc50f94b47f seem to start with only supporting jQuery 3.0 in ```Phery 3.0.0 alpha 2```, but this seems to have also landed in 3.0.0 alpha 1...

Is there a way to have a "stable" ```3.0.0 alpha 1``` with support for jQuery < 3.0? (so can the commit be reverted for tagged version ```3.0.0 alpha 1```?

![screen shot 2016-07-11 at 07 29 19](https://cloud.githubusercontent.com/assets/776405/16720737/909f551c-4739-11e6-9542-cf656aff585e.png)

**Comment by pocesar** [comment]
seems that github screwed up with their internal `git checkout -b` command heh.
I've reverted the commit, and updated the phery.min.js, re-released as 3.0.0-alpha.1 tag.

btw, I think the branch should be renamed, since it's conflicting with the tags

**Comment by holtkamp** [comment]
mm, ok, thanks for the swift response. 

a ```composer update``` with clean caches now gives a warning however:


```
- Installing phery/phery (dev-3.0.0-alpha.1 d131d8d)
    Cloning d131d8d930e6f5a659f5db2307548a6e50558fe4
fatal: reference is not a tree: d131d8d930e6f5a659f5db2307548a6e50558fe4

    Failed to download phery/phery from source: Failed to execute git checkout 'd131d8d930e6f5a659f5db2307548a6e50558fe4' -- && git reset --hard 'd131d8d930e6f5a659f5db2307548a6e50558fe4' --

fatal: reference is not a tree: d131d8d930e6f5a659f5db2307548a6e50558fe4

    Now trying to download from dist
  - Installing phery/phery (dev-3.0.0-alpha.1 d131d8d)
Downloading https://api.github.com/repos/pheryjs/phery/zipball/d131d8d930e6f5a659f5db2307548a6e50558fe4
    Downloading: 100%    
```

It seems to fall back to the zip of commit https://github.com/pheryjs/phery/commit/d131d8d930e6f5a659f5db2307548a6e50558fe4

Note sure why, maybe we have to wait a bit untill caches (at packagist.org?) expire...


About 
> btw, I think the branch should be renamed, since it's conflicting with the tags

Well, the branch name slightly differs from the tag? "3.0.0-alpha1" and 3.0.0.alpha**.**1" note the dot 😄 . But it might be a thingie. Git seems to prefer branches over tags, but still the names are different, right?

**Comment by pocesar** [comment]
I changed it, the tag and the branch had the same names
