### ISSUE TITLE
Is it possible to have PHP return an attachment as response to a Phery request?

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#51]
Just wondering/looking for confirmation, would it be possible to have PHP send back an attachment as 'response' to a Phery request?

For example, I have a HTML form which is used to configure a certain download. After submitting/POSTing the form using Phery, the user should be presented a file download. 

Experimented a bit and simply sending out some headers instead of returning the Phery response does not work. 

```php
$attachmentFilename = sprintf('%s-%s.xml', 'fileName', strftime('%Y%m%d-%H%M%S', time()));
$content = '<root><someXML/></root>;
header("Content-Type: application/xml");
header("Content-Transfer-Encoding: binary");
header(sprintf('Content-Disposition: attachment; filename=%s', $attachmentFilename));
header(sprintf('Content-Length: %d', mb_strlen($content, '8bit')));

echo $content;
```

I googled around a bit and the most [common work around is redirect the user to a specific URL](http://stackoverflow.com/questions/14774282/force-download-via-ajax-and-php) which deals with pushing the attachment, for example: domain.ext/file-controller/download/file/$temporaryFilename.ext

@pocesar, can you confirm that sending out an attachment triggering a "save as" dialog is not possible with Phery (as it uses $.ajax in the background to submit the requests)..?

**Comment by pocesar** [comment]
yes, natively $.ajax from jQuery can't handle something such as Content-Disposition without some workarounds. returning the URL they need to reach to be able to download is the right thing to do (with some sort of security mechanism, either by an unique hash in the URL or a `$_SESSION` setting)

**Comment by holtkamp** [comment]
Ok, thanks for the confirmation and clarification 😄 

What I now do is just have a redirect in the response:

```php
PheryResponse::factory()->redirect($url);
```

Works great 👍
