### ISSUE TITLE
Chaining JavaScript functions in a PheryResponse

### ISSUE THREAD

**Issue by holtkamp** [pheryjs/phery#56]
To update the possible options of a [TimePicker](http://amsul.ca/pickadate.js/time/), I am trying to get this JavaScript into a PheryResponse:

```javascript
$("#timepickerId").pickatime("picker").set("disable", [12,13,14]);
```
or
```javascript
$("#timepickerId").pickatime("picker").disable([12,13,14]);
```

I only managed this in an "ugly" way:

```php
return PheryResponse::factory()->script('$("#timepickerId").pickatime("picker").set("disable", [12,13,14]);');
```

But I was looking to something like:

```php
$disabledHours = array(13,14,15);
return PheryResponse::factory('timepickerId')->pickatime('picker')->disable($disabledHours);
return PheryResponse::factory('timepickerId')->pickatime('picker')->set('disable', $disabledHours);
```

This will generate a JavaScript error at [this line](https://github.com/pheryjs/phery/blob/f22d04625d84d4631c6b2ea0435fe6623c9b1c8e/phery.js#L1590):

```
TypeError: self.$current is undefined
if (typeof self.$current[cmd['c']] === 'function') {
```

Would it be possible? Or... Any pointers are welcome 😄

**Comment by pocesar** [comment]
is it a typo on `PheryResponse::factory('timepickerId')`? (should be `"#timepickerId"`)

you should be able to do that, because `__call` calls are trapped and made into jQuery chained calls.

**Comment by holtkamp** [comment]
OMG, totally overlooked that, sorry for wasting your time...

This works:

```php
return PheryResponse::factory('#timepickerId')->pickatime('picker')->set('disable', $disabledHours);
```

This gives a message in the console: ```no function "disable" found in object```
```php
return PheryResponse::factory('#timepickerId')->pickatime('picker')->disable($disabledHours);
```

While the [API of the TimePicker](http://amsul.ca/pickadate.js/api/) suggests this as an approach as well... Might be because of some magic interception of function calls going on there that are not "detected" by Phery? No problem, never liked magic 😄 

Thanks! Closing issue

**Comment by pocesar** [comment]
hmm it should, unless maybe `pickatime` doesn't return a jQuery method. I couldn't find any mention for `.disable()` in their API, only using `set('disable'`, maybe it's meant that way haha

**Comment by holtkamp** [comment]
guess you are right... must've been some StackOverflow stuff I thought I had seen...
