### ISSUE TITLE
get_magic_quotes_gpc removed in PHP 8

### ISSUE THREAD

**Issue by Bjoern-KCS** [pheryjs/phery#59]
Because the `get_magic_quotes_gpc` was removed in PHP 8, phery won't work anymore, without recreating this function.
IMO it would be better to check if the function exists in `Phery.php` at line 659.

**Comment by pocesar** [comment]
@Bjoern-KCS can you make a PR?

**Comment by Bjoern-KCS** [comment]
@pocesar yes, sure. I made one for the master branch.

**Comment by pocesar** [comment]
thanks!

**Comment by Bjoern-KCS** [comment]
Thanks for merging the PR.
But there ist one problem left. I cant install this new version via composer. I think you have to tag the version and update packagist.org.

**Comment by pocesar** [comment]
you're right, forgot that the actual working version is the `3.0.0-alpha2` branch. as been a while I used PHP
